# Generated by Django 5.0.4 on 2024-04-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('username', models.CharField(default='', max_length=20)),
                ('mobile', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
