# Generated by Django 5.0.4 on 2024-04-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
