# Generated by Django 5.0.4 on 2024-04-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
