# Generated by Django 5.0.4 on 2024-04-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
