# Generated by Django 5.0.4 on 2024-04-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
