# Generated by Django 5.0.4 on 2024-04-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'datas',
            },
        ),
    ]
