# Generated by Django 5.0.4 on 2024-04-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='registerform',
            old_name='Lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='registerform',
            old_name='Username',
            new_name='username',
        ),
    ]
