# Generated by Django 5.0.4 on 2024-04-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_firstname_registerform_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
