# Generated by Django 5.0.4 on 2024-04-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile_delete_registerform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
