# Generated by Django 5.0.4 on 2024-04-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
