# Generated by Django 5.0.4 on 2024-04-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
