# Generated by Django 5.0.4 on 2024-05-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0016_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'datas',
            },
        ),
    ]
