# Generated by Django 5.0.4 on 2024-05-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_registerform_city_remove_registerform_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='address',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='lastname',
        ),
    ]
